version: '3'

services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - "80:80"      # HTTP redirect
      - "443:443"    # HTTPS default port
      - "8081:8081"  # Nexus HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-cache:/var/cache/nginx
    networks:
      - pipeline
    restart: unless-stopped

networks:
  pipeline:
    external: true
